name: Pull and Pack Docker Image
on:
  workflow_dispatch:
    inputs:
      docker_images:
        description: '请填写docker镜像名称 多个用英文逗号分开'
        required: true
        default: 'alpine:latest'
      architecture:
        description: '请选择架构 (amd64 或 arm64 或 other)'
        required: true
        default: 'amd64'

jobs:
  pull_and_pack:
    runs-on: ubuntu-latest
    
    steps:

      # Step 2: Convert the comma-separated docker_images input into a JSON array and set architecture
      - name: Set up docker images array and architecture
        id: setup
        run: |
          images="${{ github.event.inputs.docker_images }}"
          json_images=$(echo "[\"$(echo $images | sed 's/,/","/g')\"]")
          architecture="${{ github.event.inputs.architecture }}"
          echo "docker_images=$json_images" >> $GITHUB_ENV
          echo "architecture=$architecture" >> $GITHUB_ENV

  # Use matrix strategy at the job level
  pull_and_pack_images:
    runs-on: ubuntu-latest
    needs: pull_and_pack  # Ensure that the first job completes before this one starts
    strategy:
      matrix:
        image: ${{ fromJson(needs.pull_and_pack.outputs.docker_images) }}
        arch: ${{ env.architecture }}
    steps:
      # Step 1: Clean Docker system
      - name: Clean Docker
        run: |
          docker system prune -a -f
          docker volume prune -f
          docker builder prune -f
          docker network prune -f
    
      # Step 3: Pull and save Docker image for each image in the matrix
      - name: Pull and Pack Docker Images
        run: |
          echo "Pulling and saving Docker image: ${{ matrix.image }} with architecture ${{ matrix.arch }}"
          docker pull "${{ matrix.image }}" --platform "linux/${{ matrix.arch }}"
          docker save "${{ matrix.image }}" -o "${{ matrix.image//[:\/]/_ }}-${{ matrix.arch }}.tar"

      # Step 4: Generate timestamp for artifact name
      - name: Generate timestamp for artifact name
        id: timestamp
        run: echo "timestamp=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      # Step 5: Upload the generated Docker image tarballs as artifacts
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-images-tar-${{ env.architecture }}-${{ env.timestamp }}
          path: "*.tar"
          retention-days: 1
          compression-level: 9
