name: Pull and Pack Docker Image
on:
  workflow_dispatch:
    inputs:
      docker_images:
        description: '请填写docker镜像名称 多个用英文逗号分开'
        required: true
        default: 'alpine:latest'
      architecture:
        description: '请选择架构 (amd64 或 arm64 或 other)'
        required: true
        default: 'amd64'

jobs:
  pull_and_pack:
    runs-on: ubuntu-latest

    steps:

    # - name: Checkout repository
    #   uses: actions/checkout@v4

    - name: Clean Docker
      run: |
        docker system prune -a -f
        docker volume prune -f
        docker builder prune -f
        docker network prune -f

    - name: Pull Docker Images and Pack
      run: |
        images="${{ github.event.inputs.docker_images }}"
        arch="${{ github.event.inputs.architecture }}"
        IFS=',' read -r -a image_array <<< "$images"
        for image in "${image_array[@]}"; do
          (docker pull "${image}" --platform "linux/${arch}" && docker save "${image}" -o "${image//[:\/]/_}-${arch}.tar") &
        done
        wait

    - name: Compress with 7z
      run: |
        sudo apt-get update && sudo apt-get install -y p7zip-full
        7z a docker-images-tar.7z *.tar -mx=9  

    - name: Generate timestamp for artifact name
      id: timestamp
      run: echo "timestamp=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-images-${{ github.event.inputs.architecture }}-${{ env.timestamp }}
        path: docker-images-tar.7z
        retention-days: 1
        compression-level: 0
